version: "3.9"

services:
  lo_python_path_app:
    env_file: .env
    network_mode: "bridge"
    # env_file: user.env
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        LO_VERSION: "7.5.5"
        CONFIG_DIR: /config
        POETRY_VER: "1.7.1"
    # user: root
    container_name: lo_python_path_app
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Etc/UTC
      - PUID=0
      - PGID=0
      - CONFIG_DIR=/config
      - DEV_CONTAINER=1
      - WORK_DIR=/workspace/lo_python_path_ext
    volumes:
      - type: bind
        source: ../
        target: /workspace/lo_python_path_ext
      - type: bind
        source: ../Documents
        target: /config/Documents
      - type: bind
        source: ../macro
        target: /config/.config/libreoffice/4/user/Scripts/python
      - type: volume
        source: app_lo_config
        target: /config
      - type: volume
        source: app_virtual_env
        target: /workspace/lo_python_path_ext/.venv
    
    ports:
      - 3050:3000
      - 3051:3001
    restart: unless-stopped

volumes:
  app_virtual_env:
  app_lo_config:
